license="MIT"

issueTrackerURL="https://github.com/fixyldev/component-viewer/issues"

[[mods]]
modId="componentviewer"
version="${version}"

displayName="Component Viewer"
description="Component Viewer is a mod for Minecraft Java Edition that allows you to view and copy components of any item stack."
logoFile="assets/componentviewer/icon.png"

displayURL="https://modrinth.com/mod/component-viewer"

authors="fixyldev"

[[mixins]]
config="componentviewer-common.mixins.json"

[[dependencies.componentviewer]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9,1.21.11)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.componentviewer]]
    modId="neoforge"
    type="required"
    versionRange="[21.9.16-beta,)"
    ordering="NONE"
    side="CLIENT"
